# Hexo Configuration

# Site
title: RP 主机博客
subtitle: blog.rpvhost.net
description:
author: RP 主机
email: admins@rpvhost.net
language: zh-CN

# URL
url: http://blog.rpvhost.net
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
per_page: 4
pagination_dir: page

# Extensions
theme: landscape

# Deployment
deploy:
  type: rsync
  host: blog.rpvhost.net
  user: rpvhost
  root: /home/rpvhost/blog-public

feed:
  type: atom
  path: atom.xml
  limit: 20
