# Header
menu:
  主页: /
  关于本站: /about
  Github: https://github.com/jysperm/RootPanel
  jp1: http://jp1.rpvhost.net
  us1: http://us1.rpvhost.net
  gs1: http://greenshadow.net

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
  - tag
  - archive

# Miscellaneous
google_analytics: UA-49193300-2
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
